version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: todo-mongo
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    container_name: todo-redis
  server:
    image: todo-be
    build:
      context: ./todo-backend
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://root:example@todo-mongo:27017/the_database?authSource=admin
      REDIS_URL: redis://todo-redis:6379
    container_name: todo-be
    depends_on:
      - mongo
      - redis
  app:
    image: todo-fe
    build:
      context: ./todo-frontend
    ports:
      - 5000:80
    container_name: todo-fe
  nginx:
    image: nginx:1.20
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reserver-proxy
volumes:
  mongo_data:
  redis_data:
